### ISSUE TITLE
noob question about installing ...

### ISSUE THREAD

**Issue by mrmay-dev** [naskio/n8n-nodes-influxdb#1]
So, I'm a little embarrassed to ask this. How do I install this node in n8n?

I'm running n8n on a DietPI (Debian based) via PM2 (https://n8n.io/blog/how-to-set-up-n8n-via-pm2/). So it's installed using `npm`.

I ran the npm command `npm i n8n-nodes-influxdb`, I also ran it with `sudo`. The node doesn't appear when searching for it.

Anyhow, hoping it's something I can do!

Thanks in advance!

**Comment by naskio** [comment]
Hello
You need to be inside the n8n package folder (which is located within your node_modules)
Something like this:
```
cd /usr/lib/node_modules/n8n && npm install n8n-nodes-influxdb
# or (if node_modules in the current folder)
cd node_modules/n8n && npm install n8n-nodes-influxdb
```
The idea is that you need to run `npm install n8n-nodes-influxdb` within the n8n package folder (should be inside  your node_modules)
Good luck

**Comment by mrmay-dev** [comment]
Aha! That makes sense. Thank you. :-)
